### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by Krato** [hallindavid/manny#10]
Hello, I can't install this package cause is not compatible with PHP 8 due composer.json restrictions. 

Is the package working with php 8? Can you update it?

Thanks!

**Comment by hallindavid** [comment]
Ok - I think this should be good to go!

Thanks Krato!

**Comment by johnnyg563** [comment]
I don't think this is updated in packagist

**Comment by hallindavid** [comment]
Thanks @johnnyg563 - I think I sorted that now.

Sorry all - I haven't really bumped too many apps up to PHP 8 yet.
