### ISSUE TITLE
Money value

### ISSUE THREAD

**Issue by theoreaves** [hallindavid/manny#15]
I need to take whatever number is entered and convert it to  a money value.  So: 457 would be 457.00, and 43.9 would be 43.90 and 44.5667 would be 44.57

How would I go about that?

Thanks!

**Comment by hallindavid** [comment]
These days, I'd actually just use the [number_format](https://www.php.net/manual/en/function.number-format.php) function.

Manny doesn't have this one, because it's pretty clean as a built in php function.

```php
$value = 44.5667

number_format($value,2);
```

**Comment by theoreaves** [comment]
You know, I was way overthinking it.  Thanks!

**Comment by hallindavid** [comment]
No worries, Happy to help!
